# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter.xci
# IP: The module: 'clkConverter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter.xci
# IP: The module: 'clkConverter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/hammi/OneDrive/Documenten/bitbucket/SchoolFPGA/SpriteBallThing/SpriteBallThing.srcs/sources_1/ip/clkConverter/clkConverter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkConverter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
