# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/vga_output.xdc

# IP: ip/clkConverter25/clkConverter25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clkConverter25 || ORIG_REF_NAME==clkConverter25} -quiet] -quiet
